 @startuml
left to right direction
skinparam packageStyle rectangle

:Arrangør:
:Deltaker:
rectangle Arrangement {

Arrangør -- (Redigere løp)
Arrangør -- (Opprette løp)
Arrangør -- (Redigere detaljer/info)
Arrangør -- (Se navn på arrangement)
Arrangør -- (Se arrangør)
Arrangør -- (Se beskrivelse)
Arrangør -- (Se tidspunkt)
Arrangør -- (Se påmeldte deltakere)
Arrangør -- (Se lokasjon)
Arrangør -- (Invitere Deltakere)
Arrangør -- (Se alle arrangementes løp)

(Se navn på arrangement) -- Deltaker
(Se arrangør) -- Deltaker
(Se beskrivelse) -- Deltaker
(Se tidspunkt) -- Deltaker
(Se påmeldte deltakere) -- Deltaker
(Se lokasjon) -- Deltaker
(Invitere Deltakere) -- Deltaker
(Se alle arrangementes løp) -- Deltaker
(Melde seg på løp) -- Deltaker
}
 @enduml