 @startuml
left to right direction
skinparam packageStyle rectangle

rectangle arrangement {
:Arrangør:

Arrangør -up- (Redigere løp)
Arrangør -up- (Opprette løp)
Arrangør -up- (Redigere detaljer/info)
Arrangør -- (Se alle arrangementes løp)
Arrangør -- (Se påmeldte deltakere)
Arrangør -- (Invitere Deltakere)
Arrangør -- (Se lokasjon)
Arrangør -- (Se beskrivelse)
Arrangør -- (Se tidspunkt)
Arrangør -- (Se arrangør)
Arrangør -- (Se navn på arrangement)

:Deltaker:

(Se navn på arrangement) -- Deltaker
(Se arrangør) -- Deltaker
(Se tidspunkt) -- Deltaker
(Se påmeldte deltakere) -- Deltaker
(Invitere Deltakere) -- Deltaker
(Se alle arrangementes løp) -- Deltaker
(Se beskrivelse) -- Deltaker
(Melde seg på løp) -- Deltaker
(Se lokasjon) -- Deltaker
}
 @enduml