@startuml
left to right direction

:Uregistrert bruker: as Uregistrert

rectangle "Brukertyper i systemet"{

    :Deltaker:
    :Arrangør:
    :Admin:

}

Admin -- (Finne Arrangementer)
Arrangør -- (Finne Arrangementer)
Deltaker -- (Finne Arrangementer)
Uregistrert -- (Finne Arrangementer)

(Redigere/slette innhold) -up- Admin

(Redigere brukerkonto) -- Deltaker
(Redigere brukerkonto) -- Arrangør
(Opprette brukerkonto) -- Uregistrert

(Logge inn) -- Deltaker
(Logge inn) -- Arrangør
(Logge inn) -- Admin

(Melde seg på arrangementer) -- Deltaker

Arrangør -- (Opprette arrangementer)

@enduml