@startuml
left to right direction

rectangle Brukertyper{

    :Deltaker:
    :Arrangør:
    :Admin:
    :Uregistrert bruker: as Uregistrert

}

Admin --- (Finne Arrangementer)
Arrangør --- (Finne Arrangementer)
Deltaker --- (Finne Arrangementer)
Uregistrert --- (Finne Arrangementer)

(Redigere brukerkonto) -- Deltaker
(Redigere brukerkonto) -- Arrangør
(Redigere brukerkonto) -- Admin
(Opprette brukerkonto) -- Uregistrert

(Logge inn) --- Deltaker
(Logge inn) --- Arrangør
(Logge inn) --- Admin

(Melde seg på arrangementer) -- Deltaker

Arrangør -- (Opprette arrangementer)

@enduml