
@startuml
class Bruker {
 - navn
 - email
 - password
 + salt
 {static}hashPassword()
 {static} finnBruker(email:String)
 {static} sjekkPassord(password:String, bruker:Bruker)
}

class Arrangement {
   flightNumber : Integer
   departureTime : Date
   {static} numberOfFlights : int
}


Dummy <|-- Flight

@enduml
