@startuml
partition Bruker {
(*) --> "trykker på arrangement"
"trykker på arrangement" --> "Trykker på løp"
--> "Trykker på meld meg på"
}
if "Bruker er av typen deltager" then
partition Deltager {
  -->[true] "Bruker meldt på"
  -->[avslutter process] (*)
}
else
partition Uregistrert {
  ->[false] "Bruker sendt til registrering"
  --> "bruker fyller ut og sender inn registreringskjema"
  --> "Bruker meldt på"
  }
endif
@enduml