@startuml


softwareengineering.model.Bruker -> Frontend: Gir brukerinfo
Frontend -> Backend: Sender brukerinfo
Backend -> Backend: Sjekker brukerinfo

alt gyldig informasjon
 Backend -> Backend: Oppretter bruker
 Backend --> Frontend: bruker opprettet
 Frontend --> softwareengineering.model.Bruker: bruker opprettet
else  ikke gyldig informasjon
 Backend --> Frontend: ugyldig informasjon
 Frontend --> softwareengineering.model.Bruker: ugyldig informasjon
end


@enduml